# Generated by Django 4.2.4 on 2023-09-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=25)),
                ('qualification', models.CharField(choices=[('ssc', 'SSC'), ('intermediate', 'INTERMEDIATE'), ('degree', 'DEGREE'), ('btech', 'BTECH')], default='ssc', max_length=50)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('is_admin', models.BooleanField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'db_table': 'Credentials',
            },
        ),
    ]
