# Generated by Django 4.2.4 on 2023-09-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
