# Generated by Django 4.2.4 on 2023-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_credentials_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10),
        ),
    ]
